server:
  port: 8888

spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  freemarker:
    cache: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql.sqlpub.com:3306/backendtest?characterEncoding=UTF8&useSSL=false
    username: dbadmin
    password: 411fa14dbeae913b
    type: com.alibaba.druid.pool.DruidDataSource




mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml