/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElFooer: typeof import('element-plus/es')['ElFooer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomePic: typeof import('./src/components/HomePic.vue')['default']
    Icon1Administrator: typeof import('./src/components/icons/Icon1Administrator.vue')['default']
    Icon2Administrator: typeof import('./src/components/icons/Icon2Administrator.vue')['default']
    Icon3Administrator: typeof import('./src/components/icons/Icon3Administrator.vue')['default']
    Icon4Administrator: typeof import('./src/components/icons/Icon4Administrator.vue')['default']
    Icon5Administrator: typeof import('./src/components/icons/Icon5Administrator.vue')['default']
    Icon6Administrator: typeof import('./src/components/icons/Icon6Administrator.vue')['default']
    IconBubble: typeof import('./src/components/icons/IconBubble.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconReturn: typeof import('./src/components/icons/IconReturn.vue')['default']
    IconSamperVaccinum: typeof import('./src/components/icons/IconSamperVaccinum.vue')['default']
    IconSamplerNucleicAcid: typeof import('./src/components/icons/IconSamplerNucleicAcid.vue')['default']
    IconScanQRCode: typeof import('./src/components/icons/IconScanQRCode.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    RegisterForm: typeof import('./src/components/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SamperVaccinum: typeof import('./src/components/icons/SamperVaccinum.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
