/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElFooer: typeof import('element-plus/es')['ElFooer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomePic: typeof import('./src/components/HomePic.vue')['default']
    IconBubble: typeof import('./src/components/icons/IconBubble.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconProfile: typeof import('./src/components/icons/IconProfile.vue')['default']
    IconQrCode: typeof import('./src/components/icons/IconQrCode.vue')['default']
    IconQuery: typeof import('./src/components/icons/IconQuery.vue')['default']
    IconReturn: typeof import('./src/components/icons/IconReturn.vue')['default']
    IconRing: typeof import('./src/components/icons/IconRing.vue')['default']
    IconSamperVaccinum: typeof import('./src/components/icons/IconSamperVaccinum.vue')['default']
    IconSamplerNucleicAcid: typeof import('./src/components/icons/IconSamplerNucleicAcid.vue')['default']
    IconScanQRCode: typeof import('./src/components/icons/IconScanQRCode.vue')['default']
    IconSite: typeof import('./src/components/icons/IconSite.vue')['default']
    IconSiteCode: typeof import('./src/components/icons/IconSiteCode.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    RegisterForm: typeof import('./src/components/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SamperVaccinum: typeof import('./src/components/icons/SamperVaccinum.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
